env:
  matrix:
    - MYCONDAPY=3.5
    - MYCONDAPY=3.6
    - MYCONDAPY=3.7
  global:
    - secure: "Rrseenv58UBt/+sW3p2ToaksHes5Jr3OqLEa1pglDSX347u1rUfyBr2L358dVJgw7nkXXSaTfQ9hz5cboVmLIToJCaY3W82I3vaRDvLhbEs4bj/lLa8p3ZFx4klnIz4cntY3296xaa05AYJ3ghHmeOIKz0dBrfv3snrz2L//Foxgli9I2iSD+9Wt2yN567+ypWhGjfa4VOrU4DiR+hdCKwY2kX6/JtH6ZeOHvnefyDMU3Seu0qmZr+NzucRsMWNs1NwuiejA2/4jnix2zu3DIOGQgUV0IqqeeEXGAKAs9gf+6K5RGSDs3OwKhiAmeoiFs0jYNkT725NHuQfb7h2KVMz1lAZS1wt2x0aEIVvT7loIYdiXNvUVAZ/XdT15PhRw/HqREkwviUQtsDzMyGaxComH6in2+8C5IuNunawhWmtOdzSTuUOKA4332vh02acVc/r0Pj70ZJJiycg0ARdCcMh++yJFercz+KBPAU/KjM5qbaMvN3gx8aY9i3fEQZcVrRzPqBOR77UC/q1D0VdULXUXzSi3JtImx/ToN4uPAakE4G6XGMf3ApGxGiHC5i6m8x3LVqOS0wjZyBZU86TrU0c1wwHCrBADyounTTgXqxitAYZA2YrCo8HCH/IXYFJZ2iOkQelkMHTvovgejLNymVOXM9ryJfQFujZr4jzUKMk=" 
    - PROJECT_NAME=libmetgem
    - GITHUB_REPO_NAME=metgem/libmetgem
    - PYPI_LOGIN=n-elie
    - CFLAGS=-std=c++11
    - CXXFLAGS=-std=c++11
    
language: generic
os:
  - linux
  - osx
osx_image:
  - xcode8
compiler: gcc
sudo: false

cache:
    directories:
        - $HOME/download # Sufficient to add miniconda.sh to TRAVIS cache.
        - $HOME/miniconda # Add the installation to TRAVIS cache.
        
before_cache:
    - if ! [[ $TRAVIS_TAG ]]; then rm -rf $HOME/miniconda/conda-bld; fi
    - rm -rf $HOME/miniconda/locks $HOME/miniconda/pkgs $HOME/miniconda/var $HOME/miniconda/conda-meta/history
    
before_install:
    - if test -e $HOME/miniconda/bin; then
        echo "miniconda already installed.";
      else
        echo "Installing miniconda.";
        rm -rf $HOME/miniconda;
        mkdir -p $HOME/download;
        if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
        if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
        fi;
        bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
      fi;
    - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        export CC=gcc-4.9;
        export CXX=g++-4.9;
      fi;
    
install:
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    
    # Configure conda and get a few essentials
    - conda config --set always_yes yes
    #- conda config --add channels metgem
        
    - conda remove --name test-env --all
    - conda create -q -n test-env python=${MYCONDAPY}
    - source activate test-env
    
    - conda install -q conda conda-build conda-verify anaconda-client numpy setuptools cython
    - pip install pyteomics pytest pylint pytest-pylint pytest-cov codecov
    
script:
    - python setup.py build_ext -i --define CYTHON_TRACE_NOGIL
    - python setup.py install
    - pytest --pylint --pylint-rcfile=.pyrcfile --pylint-error-types=EF libmetgem
    - cd tests;pytest --cov=libmetgem
    
    # Make CPP and PY source package for github deployment
    - if [[ $TRAVIS_TAG ]]; then
        python setup.py sdist;
      fi
        
after_success:
    # Upload the coverage analysis
    - codecov -e PYTHON=$MYCONDAPY
